### ISSUE TITLE
使用influxdb有感

### ISSUE THREAD

**Issue by vicanso** [vicanso/articles#4]
大家对influxdb在使用过程中有所疑问的可在此提出

**Comment by Newt0n** [comment]
InfluxDB 开源版本不支持集群了？对此有没有方案？

**Comment by vicanso** [comment]
@Newt0n 如果只是高可用的需求，那么可以使用[influxdb-relay](https://github.com/influxdata/influxdb-relay)，如果真的是性能跟上不，那么就分多`db`，不同的`db`部署在不同的机器上。

在使用多`db`部署多机器之前，先看看是否直接在记录统计上做优化，我自己的应用是使用`write multiple points`的方式，每个统计先写入到队列中，等队列长度达到100（或者30秒之内未有其它统计进入队列），再写到`influxdb`。使用此方式，我现在应用的情况是大概每天2千万多的统计点写入，使用`influxdb-relay`对接两个`influxdb`，两台机器上完全感受不到性能上的压力

**Comment by ULis3h** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
jseanchuang, @ryan-rozario, @tariqismail, @NimrodHunter, @coOps5566, @Jaybee020, @mmdhrumil, @chavestech, @baahkusi, @AashayBhupendraDoshi, @heronimus, @rabahs, @gomtak, @nicoglennon, @zackhtw, @anoushk1234, @CharlesMariga, @Erased0Citizen, @ymekuria, @zpjayyy

**Comment by CharlesMariga** [comment]
> Hello,
> 
> We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!
> 
> As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:
> 
> * Health insurance coverage
> * Retirement savings plan
> * Flexible work schedule
> * Generous vacation and paid time off
> * Professional development opportunities
> 
> To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.
> 
> Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.
> 
> **Important:** You have 24 hours to complete the application process.
> 
> If you have any questions or need further information, please don't hesitate to contact us.
> 
> Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.
> 
> Best regards, GitHub Recruitment Team jseanchuang, @ryan-rozario, @tariqismail, @NimrodHunter, @coOps5566, @Jaybee020, @mmdhrumil, @chavestech, @baahkusi, @AashayBhupendraDoshi, @heronimus, @rabahs, @gomtak, @nicoglennon, @zackhtw, @anoushk1234, @CharlesMariga, @Erased0Citizen, @ymekuria, @zpjayyy

This is a scum. Don't dare fall fro it.
